spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## 43.136.124.89   线上的
    ## 192.168.10.34
    url: jdbc:mysql://43.136.124.89:3306/movie?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: lyp20015018
    druid:
      initial-size: 5   #连接池配置
      max-active: 100
      max-wait: 12000
######################################   mybatis-plus集成  #####################################
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package:
    - cn.gun.pojo
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#########################################  日志    ####################################
logging:
  level:
    org.springfromework.web: ERROR
    org.mybatis: info
